apiVersion: v1
kind: Pod
metadata:
  labels:
    run: appbiomedicalekube
  name: appbiomedicalekube
spec:
  containers:
  - image: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    name: appbiomedicalekube
  restartPolicy: Always

