apiVersion: v1
kind: Pod
metadata:
  labels:
    run: appbiomedicalekube
  name: appbiomedicalekube
spec:
  containers:
  - image: registry.gitlab.com/fatimazahra20mouket/fatimazahrmoukettemplate/master:latest
    name: appbiomedicalekube
  imagePullSecrets:
    - name : app-secret
