apiVersion: v1
kind: Pod
metadata:
  labels:
    run: appbiomedicaleku
  name: appbiomedicaleku
spec:
  containers:
  - image: registry.gitlab.com/fatimazahra20mouket/fatimazahrmoukettemplate/master:latest
    name: appbiomedicaleku
  restartPolicy: Always
  imagePullSecrets:
    - name : app-secre
